name: barbarian_example
description: Demo of barbarian use to help

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  barbarian:
    path : ../

flutter:

  uses-material-design: true